### ISSUE TITLE
Distribute as ES module (as well?)

### ISSUE THREAD

**Issue by kenchris** [foldable-devices/spanning-css-polyfill#3]
It has become quite popular to use ES modules for distribution with tools built around it like pika.dev

All evergreen browsers support modules, so this should be no issue.

**Comment by zouhir** [comment]
agree, happy to distribute es modules, I will add that.

**Comment by darktears** [comment]
We should probably also put that on npm to avoid people manually copying around the polyfill.

**Comment by darktears** [comment]
Fixed package is live there : https://www.npmjs.com/package/spanning-css-polyfill
