### ISSUE TITLE
polyfill doesn't work with style sheets built in JS

### ISSUE THREAD

**Issue by jspurlin** [foldable-devices/spanning-css-polyfill#5]
[index.html.txt](https://github.com/zouhir/spanning-css-polyfill/files/4047487/index.html.txt)

In my usage, I'm building a stylesheet dynamically in JS and noticed that the polyfill requires the styles to be actually in the style element in the DOM. I've attached a repro with the example page (converted to build the stylesheet in JS).

This will add unneeded complexity to our code until this is fixed :(

**Comment by zouhir** [comment]
thanks @jspurlin -- I will work on this when I'm back!

**Comment by jspurlin** [comment]
Another interesting aspect about this is that invalid media queries created in js get automatically converted to `@media not all` by the browser so what in the stylesheet in memory isn't what's expected

**Comment by darktears** [comment]
For the same reason (requiring your style to be part of the main DOM) you can't also use the polyfill in a web-component. (for example say you're using a lit-element where you want to use the newly defined media queries in your css declarations)

**Comment by zouhir** [comment]
@darktears I opened a separate issue to discuss how web I can make it work with web components, I'd love to understand more and fix.

@jspurlin : will css-in-js insert what ever rules & media queries you write in your code editor as-is? I know that in the browser CSSOM won't understand that media query, this is why I query the stylesheets as text and process it instead of using existing CSSOM JS APIs.

**Comment by jspurlin** [comment]
No, our styles definitions in typescript don't get converted correctly in resulting styling. Regardless. I'm building the styling completely dynamically (not using any css-in-js type styling and instead building a stylesheet). I know one of my other engineers tried using a css-in-js type styling and he was unsucessful in getting things working. We can follow up offline to get more details here

**Comment by darktears** [comment]
After investigating https://github.com/foldable-devices/spanning-css-polyfill/pull/8 with my colleague @kenchris we found that anything that goes through CSSStyleSheet and then use `parse` will ultimately get parsed by the browser engine and per spec recommendation unknown @media query rules will be replaced by `not all`. That gives 0 chance for the polyfill to catch up the rules (say as adopted style sheet for e.g.) to replace them. It's too late...

The only workaround I can find is if the polyfill provides a method to pass your CSSStyleSheet as a parameter to update what's inside it before it gets parsed by the web engine.

**Comment by kenchris** [comment]
@darktears I made it work for both vanilla web components or lit-element ones (which can be backed by adoptedStyleSheets). It seems to work quite OK

**Comment by darktears** [comment]
We've added a special note let us know if that works for your use case : https://github.com/foldable-devices/spanning-css-polyfill#special-note-for-handling-of-stylesheets-manually-constructed-from-css-rules

In the meantime I'll close it.
